version: '3'
services:
  backend:
    environment:
      - PORT=4000
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - '4000:4000'
  frontend:
    environment:
      - PORT=3000
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - '3000:3000'
